version: "3"
services: 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - node
    ports:
      - "80:80" # docker 內部 80 指向 localhost 的80
  redis:
    image: redis:5.0.7
  node:
    build: .
    ports:
      - 3000:3000



